### ISSUE TITLE
Backdoor

### ISSUE THREAD

**Issue by Breathless** [OlegKunitsyn/elasticsearch-browser#14]
После того как поставил ваш плагин, получил шеллкод на сервер, запустившийся от юзера elasticsearch. Подробностей предоставить не смогу (почистил), но шелл залили в /tmp.
Есть идеи?

**Comment by OlegKunitsyn** [comment]
Please write in English to share this information with others. The plugin is single html file that calls single JS file http://cdn.sencha.com/ext/gpl/4.2.0/ext-all.js by Sencha Inc. Your report is irrelevant to the issue
