### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by craigcosmo** [OlegKunitsyn/elasticsearch-browser#15]
It wouldn't install

![screen shot 2015-07-26 at 9 55 05 pm](https://cloud.githubusercontent.com/assets/538657/8894428/11529ac4-33e1-11e5-9cfb-3dda2e0389c2.png)

**Comment by OlegKunitsyn** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/1.6/modules-plugins.html
