### ISSUE TITLE
Installs fine, no display in browser

### ISSUE THREAD

**Issue by hinkman** [OlegKunitsyn/elasticsearch-browser#5]
Given how easy the setup of this should be, I am probably doing something really stupid but sure can't see it.

Broswer: Firefox 21.0 and Safari 5.1.9
ElasticSearch: 0.90.1

Installation seems to work fine (image browser_install.png):
![browser_install](https://f.cloud.github.com/assets/4512730/663112/4cb7c89e-d765-11e2-871b-f66b423642fd.png)

I can confirm data in the selected database/table via head plugin - note connect info, _index and _type in image head_output.png):
![head_output](https://f.cloud.github.com/assets/4512730/663131/afc8e382-d765-11e2-8fc5-96b789c85313.png)

yet I get nothing but a blank page when attempting to access the browser plugin:
![blank_firefox](https://f.cloud.github.com/assets/4512730/663137/d4995e4e-d765-11e2-9cbd-0256b4a7a0f6.png)

ElasticSearch logs show nothing in relation to this. Any suggestions are appreciated.

**Comment by spinx** [comment]
Same for me. Don't have any dots or spaces in my properties.

**Comment by Henri85** [comment]
This is a serious issue.

I understand: ExtJS cannot handle dots in properties. However, this problem appears when you use nested data structure.

*Nested data structures in json means using of dot separator.* ES supports nested data, but the ES Browser doesn't because the 'cannot-has-dots-in-properties'.

**Comment by OlegKunitsyn** [comment]
Yes. The limitation of this plugin.

**Comment by Henri85** [comment]
Ok, possible solution: using parent-child structure instead of nested data.

**Comment by jdnurmi** [comment]
Just to join the party, I end up receiving a similar error for different reasons - our ES cluster is behind SSL and the plugin appears to attempt to pull http:// dependencies, causing chrome to reject them:

Mixed Content: The page at 'https://REDACTED/_plugin/browser/?database=elastalert_status&table=elastalert' was loaded over HTTPS, but requested an insecure script 'http://cdn.sencha.com/ext/gpl/4.2.0/ext-all.js'. This request has been blocked; the content must be served over HTTPS

I imagine making the JS includes protocol relative (//cdn.sencha.com/) would work, but I've not tried it.

**Comment by OlegKunitsyn** [comment]
http: removed

**Comment by OlegKunitsyn** [comment]
Discontinued. Please use https://kaizen.artcom-venture.de
